#!/bin/bash
ppm="$HOME/.ppm"
function parse_yaml {
   local prefix=$2
   local s='[[:space:]]*' w='[a-zA-Z0-9_]*' fs=$(echo @|tr @ '\034')
   sed -ne "s|^\($s\):|\1|" \
        -e "s|^\($s\)\($w\)$s:$s[\"']\(.*\)[\"']$s\$|\1$fs\2$fs\3|p" \
        -e "s|^\($s\)\($w\)$s:$s\(.*\)$s\$|\1$fs\2$fs\3|p"  $1 |
   awk -F$fs '{
      indent = length($1)/2;
      vname[indent] = $2;
      for (i in vname) {if (i > indent) {delete vname[i]}}
      if (length($3) > 0) {
         vn=""; for (i=0; i<indent; i++) {vn=(vn)(vname[i])("_")}
         printf("%s%s%s=\"%s\"\n", "'$prefix'",vn, $2, $3);
      }
   }'
}
function interrupt() {
    rm -rf "$ppm/.fetch"
    rm -rf "$ppm/.tar"
    exit
}
function parse {
    eval $(parse_yaml $1 "PKG_")
}
function ppmhelp {
    echo "PPM v1"
    echo "  ppm install/in <package>     | install a package"
    echo "  ppm remove/rm  <package>     | remove a package"
    echo "  ppm installed                | list installed packages"
}
function desktop_gen {
	>"$HOME/.local/share/applications/$PKG_meta_name.desktop"
	echo "[Desktop Entry]" >> "$HOME/.local/share/applications/$PKG_meta_name.desktop"
	echo "Name=$PKG_desktop_name" >> "$HOME/.local/share/applications/$PKG_meta_name.desktop"
	echo "Type=$PKG_desktop_type" >> "$HOME/.local/share/applications/$PKG_meta_name.desktop"
	echo "Exec=$PKG_desktop_exec" >> "$HOME/.local/share/applications/$PKG_meta_name.desktop"
	echo "Icon=$PKG_desktop_icon" >> "$HOME/.local/share/applications/$PKG_meta_name.desktop"
	echo "GenericName=$PKG_desktop_generic" >> "$HOME/.local/share/applications/$PKG_meta_name.desktop"
	echo "Terminal=$PKG_desktop_terminal" >> "$HOME/.local/share/applications/$PKG_meta_name.desktop"
	sudo update-desktop-database
}
trap "interrupt" INT
case "$1" in
    read)
        parse_yaml $2 "PKG_"
    ;;
    install|in)
        parse $2
        if ls "$ppm/.pkgs" | grep "$PKG_meta_name"; then
            echo "Already installed."
            exit
        fi
        mkdir -p "$ppm/.fetch"
        wget -P "$ppm/.fetch" "$PKG_source_url"
        mkdir -p "$ppm/.pkgs/$PKG_meta_name"
        if [[ "$PKG_source_tar" == "yes" ]]; then
            mkdir -p "$ppm/.tar"
            mv "$ppm/.fetch/$PKG_source_filename" "$ppm/.tar"
            tar -xvf "$ppm/.tar/$PKG_source_filename" "$ppm/.tar"
            rm "$ppm/.tar/$PKG_source_filename"
            mv "$ppm/.tar"* "$ppm/.pkgs/$PKG_meta_name"
            # TODO: make desktop entry
        else
            mv "$ppm/.fetch/$PKG_source_filename" "$ppm/.pkgs/$PKG_meta_name"
            # TODO: make desktop entry
        fi
	desktop_gen
    ;;
    remove|rm)
        if ls "$ppm/.pkgs" | grep "$2"; then
            {
            rm -rf "$ppm/.pkgs/$2"
	    rm "$HOME/.local/share/applications/$PKG_meta_name.desktop"
            }&>/dev/null
        else
            echo "not found"
        fi
    ;;
    installed)
        ls "$ppm/.pkgs" | cat
    ;;
    *)
        ppmhelp
    ;;
esac
rm -rf "$ppm/.fetch"
rm -rf "$ppm/.tar"
trap SIGINT
